# see
# https://docs.github.com/en/actions/using-workflows/reusing-workflows
# https://rakesh-suryawanshi.medium.com/unit-testing-report-with-github-actions-7216f340044e
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net#building-and-testing-your-code

on:
  workflow_call:

name: reusable test runner

jobs:
  run_tests:
    name: run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [
          { tfm: net8.0, version: '8.0.x' },
        ]
    env:
      BUILD_CONFIG: Release
      SOLUTION: MagicxorAnalyzer.CSharp.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet.version }}

    - name: Display dotnet version
      run: |
        echo "matrix dotnet version: ${{ matrix.dotnet.version }}"
        dotnet --version

    - name: Run tests
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --framework ${{ matrix.dotnet.tfm }} --logger trx --results-directory "TestResults-${{ matrix.dotnet.version }}" /p:CollectCoverage=true

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: dotnet-test-results-${{ matrix.dotnet.version }}
        path: TestResults-${{ matrix.dotnet.version }}

    - name: Publish test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: dotnet-test-results-${{ matrix.dotnet.version }}
        path: "**/*.trx"
        reporter: dotnet-trx
        fail-on-error: true
